apiVersion: v1
kind: Secret
metadata:
  name: user-service-credentials
  namespace: user-system
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://user-database.user-system.svc.cluster.local:3306/users?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
