apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # JWT secrets
  jwt-secret: "my-super-secret-jwt-signing-key-2024"
  jwt-expiration: "86400000"

  # RabbitMQ credentials
  rabbitmq-user: "admin"
  rabbitmq-password: "password"
