apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
type: Opaque
stringData:
  # MySQL credentials (User Service)
  mysql-user: "admin"
  mysql-password: "secret"
  mysql-database: "mydb"

  # PostgreSQL credentials (Product Service)
  postgres-user: "productservice"
  postgres-password: "password"
  postgres-database: "productdb"

  # MongoDB credentials (Order Service)
  mongo-root-user: "root"
  mongo-root-password: "rootpassword"
  mongo-database: "orderdb"
