apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  application.yaml: |  # Database configuration
    DB_HOST: "mysql"
    DB_PORT: "3306"
    DB_NAME: "userdb"

    # Application configuration
    SERVER_PORT: "8080"
    LOG_LEVEL: "INFO"

    # RabbitMQ configuration
    RABBITMQ_HOST: "rabbitmq"
    RABBITMQ_PORT: "5672"

    JWT_SECRET: "your_jwt
