apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - virtual-service.yaml
  - database.yaml
  - product-app-secret.yaml
patches:
  - path: database-patch.yaml
    target:
      kind: Cluster
      name: product
